### ISSUE TITLE
UI rewrite tracking issue

### ISSUE THREAD

**Issue by spotlightishere** [OpenShopChannel/OSCHomebrewBrowser#7]
I hope this helps to explain the issue:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/10055256/179324815-9063aa2a-389d-4277-be85-ff9c75530325.png">

This issue exists to track progress while rewriting the UI. Some suggested focus areas:
 - [ ] Separate pagination-based components into their own function
 - [ ] Have 4 line descriptions
 - [ ] Less clutter with code

More should be commented/edited on to this issue as time progresses.
